# Versão exata solicitada
FROM node:25-alpine

WORKDIR /app

# O comando CMD aqui é apenas um placeholder.
# O comando real de execução (npm run dev) está no docker-compose.yml
CMD ["npm", "run", "dev", "--", "--host"]