# Generated by Django 6.0.1 on 2026-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('conteudo', models.TextField()),
                ('resumo', models.TextField(blank=True, null=True)),
                ('link_original', models.URLField(max_length=1000)),
                ('sentimento', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('NEU', 'Neutro')], default='NEU', max_length=3)),
                ('fonte_nome', models.CharField(help_text='Ex: G1, Globo Minas', max_length=100)),
                ('data_publicacao', models.DateTimeField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
