# Generated by Django 6.0.3 on 2026-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
